version: '3.8'

services:
  postgres:
    image: postgres
    container_name: edu-postgres
    environment:
      POSTGRES_USER: eduadmin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: edu_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
